In [ ]:
import numpy as np
n1 = np.array(range(24))
print(n1)

n2 = n1.reshape(3,8)
print(n2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [ ]:
# n1.rehape(3,9)는 오류
# -1를 넣어 알아서 맞춰줄 수 있다 그렇다면 둘다 -1이면?
n1.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
n3=n1.reshape(2,-1,4)
print(n3)
print(n3.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [ ]:
n3.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
x1=np.arange(28).reshape(7,-1)
x1_T = x1.T

print(x1,'\n')
print(x1_T,'\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]] 

[[ 0  4  8 12 16 20 24]
 [ 1  5  9 13 17 21 25]
 [ 2  6 10 14 18 22 26]
 [ 3  7 11 15 19 23 27]] 



In [ ]:
print(n3)
print(n3.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [ ]:
n4 = np.transpose(n3,(1,2,0))
print(n4)
print(n4.shape)

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
(3, 4, 2)


In [ ]:
print(n2)
print(n2.reshape(4,6))
print(n2.transpose(1,0))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  8 16]
 [ 1  9 17]
 [ 2 10 18]
 [ 3 11 19]
 [ 4 12 20]
 [ 5 13 21]
 [ 6 14 22]
 [ 7 15 23]]


In [ ]:
x1=np.array([0,1,2])
print(x1)
print("shape:",x1.shape)
print("---------")
x1_1=np.expand_dims(x1,axis=0)
print(x1_1)
print("shape:",x1_1.shape)
print("---------")
x1_2=np.expand_dims(x1,axis=1)
print(x1_2)
print("shape:",x1_2.shape)
print("---------")

[0 1 2]
shape: (3,)
---------
[[0 1 2]]
shape: (1, 3)
---------
[[0]
 [1]
 [2]]
shape: (3, 1)
---------


In [ ]:
x1_3=np.array([[0,1,2],[3,4,5]])
print(x1_3)
print("shape:",x1_3.shape)
print("---------")

x1_4=np.expand_dims(x1_3,axis=0)
print(x1_4)
print("shape:",x1_4.shape)
print("---------")

x1_5=np.expand_dims(x1_3,axis=1)
print(x1_5)
print("shape:",x1_5.shape)
print("---------")

[[0 1 2]
 [3 4 5]]
shape: (2, 3)
---------
[[[0 1 2]
  [3 4 5]]]
shape: (1, 2, 3)
---------
[[[0 1 2]]

 [[3 4 5]]]
shape: (2, 1, 3)
---------


In [ ]:
x2 = np.array([0,1,2])
print(x2)
print("shpae:",x2.shape)

x2_1 = x2[np.newaxis]
print(x2_1)
print("shape:",x2_1.shape)
print("---------")
x2_2 = x2[np.newaxis,:]
print(x2_2)
print("shape:",x2_2.shape)
print("---------")
x2_3 = x2[:,np.newaxis]
print(x2_3)
print("shape:",x2_3.shape)
print("---------")

[0 1 2]
shpae: (3,)
[[0 1 2]]
shape: (1, 3)
---------
[[0 1 2]]
shape: (1, 3)
---------
[[0]
 [1]
 [2]]
shape: (3, 1)
---------


In [ ]:
x3 = np.array([[0,1,2],[3,4,5]])
print(x3)
print("shape:",x3.shape)
print("---------")
x3_1 = x3[np.newaxis]
print(x3_1)
print("shape:",x3_1.shape)
print("---------")
x3_2 = x3[np.newaxis,:,:]
print(x3_2)
print("shape:",x3_2.shape)
print("---------")

[[0 1 2]
 [3 4 5]]
shape: (2, 3)
---------
[[[0 1 2]
  [3 4 5]]]
shape: (1, 2, 3)
---------
[[[0 1 2]
  [3 4 5]]]
shape: (1, 2, 3)
---------


In [ ]:
#세번째 축에 차원을 추가로 끼워넣음
x3_3 = x3[:,:,np.newaxis]
print(x3_3)
print("shape:",x3_3.shape)
print("---------")
#두번째 축에 차원을 추가로 끼워넣음
x3_4 = x3[:,np.newaxis,:]
print(x3_4)
print("shape:",x3_4.shape)
print("---------")

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
shape: (2, 3, 1)
---------
[[[0 1 2]]

 [[3 4 5]]]
shape: (2, 1, 3)
---------


In [ ]:
#VSTACK
n5 = np.arange(1,7).reshape(2,3)
n6 = np.arange(7,16).reshape(3,3)

print(n5)
print(n6)
print("---------")

#열의 사이즈가 같으면 vstack으로 쌓을 수 있다
n7 = np.vstack([n5,n6])
print(n7)

#행렬과 벡터의 연결도 가능하다
n8 = np.arange(1,4)
np.vstack([n7,n8])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]
---------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [ 1,  2,  3]])

In [ ]:
#HSTACK
n9 = np.arange(1,7).reshape(2,3)
n10 = np.arange(7,15).reshape(2,4)

print(n9)
print(n10)

n11=np.hstack([n9,n10])
print(n11)
print("---------")

n12=np.array(range(1,15)).reshape(2,-1)
print(n12)
print("---------")

np.hstack([n11,n12])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9 10]
 [11 12 13 14]]
[[ 1  2  3  7  8  9 10]
 [ 4  5  6 11 12 13 14]]
---------
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
---------


array([[ 1,  2,  3,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6, 11, 12, 13, 14,  8,  9, 10, 11, 12, 13, 14]])

In [ ]:
#Broadcasting
n13 = np.array([1,2,3,4,5])
print(n13*2)
print(n13+2)

n14 = np.arange(1,10).reshape(3,3)
print(n14)
print("---------")

n15=np.arange(3)
print(n15)
print("---------")
print(n14+n15)

n16=np.arange(3).reshape(3,1)
print(n16)
print(n16.shape)
print("---------")
n17=np.arange(3).reshape(1,3)
print(n17)
print(n17.shape)
print("---------")
print(n16+n17)

[ 2  4  6  8 10]
[3 4 5 6 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------
[0 1 2]
---------
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
[[0]
 [1]
 [2]]
(3, 1)
---------
[[0 1 2]]
(1, 3)
---------
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
#Broadcasting Error
n18 = np.arange(1,13).reshape(4,3)
print(n18)
print("---------")
n19=np.arange(4)
print(n19)
# print(n18+n19) #Error

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
---------
[0 1 2 3]


In [ ]:
n20 = np.arange(6).reshape(3,2)
print(n20)
print(n20.shape)
print("---------")
n21 = np.arange(3).reshape(1,3)
print(n21)
print(n21.shape)
print("---------")
# print(n20+n21) #Error

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
---------
[[0 1 2]]
(1, 3)
---------


In [ ]:
#연습문제
n22 = np.arange(1,13).reshape(3,4)
print(n22)
print(n22.shape)
print("****************")
n23=n22.reshape(2,-1)
print(n23)
print(n23.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
****************
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
