In [ ]:
import numpy as np
input_data = np.array([
[[1, 2, 3, 0],
[0, 1, 2, 3],
[3, 0, 1, 2],
[2, 3, 0, 1]],
[[1, 3, 2, 0],
[0, 1, 3, 2],
[2, 0, 3, 1],
[3, 2, 1, 0]],
[[2, 3, 1, 0],
[0, 2, 3, 1],
[1, 0, 2, 3],
[3, 1, 0, 2]]
])
input_data

array([[[1, 2, 3, 0],
        [0, 1, 2, 3],
        [3, 0, 1, 2],
        [2, 3, 0, 1]],

       [[1, 3, 2, 0],
        [0, 1, 3, 2],
        [2, 0, 3, 1],
        [3, 2, 1, 0]],

       [[2, 3, 1, 0],
        [0, 2, 3, 1],
        [1, 0, 2, 3],
        [3, 1, 0, 2]]])

In [ ]:
kernel = np.array([
[[1, -1, 1],
[0, 1, -1],
[-1, 0, 1]],
[[-1, 1, 0],
[1, -1, 0],
[0, 1, -1]],
[[0, -1, 1],
[1, 0, -1],
[-1, 1, 0]]
])
kernel

array([[[ 1, -1,  1],
        [ 0,  1, -1],
        [-1,  0,  1]],

       [[-1,  1,  0],
        [ 1, -1,  0],
        [ 0,  1, -1]],

       [[ 0, -1,  1],
        [ 1,  0, -1],
        [-1,  1,  0]]])

In [ ]:
#출력 데이터 초기화
output_data = np.zeros((2, 2), dtype=np.int16) # 음수 표현을 위해 -32768 ~ 32767까지 표현할 수 있는 int16을 사용
# 합성곱 연산 수행
for y in range(2): # 출력 데이터의 높이 (4-3+1=2)
  for x in range(2): # 출력 데이터의 너비 (4-3+1=2)
    roi = input_data[:, y:y+3, x:x+3] # 현재 위치에서 3x3 영역 추출
    filtered = roi * kernel # (3x3x3) * (3x3x3)의 합성곱 (모든 채널 연산)
    conv_value = np.sum(filtered) # 요소별 곱셈 후 모든 결과들을 더함
    output_data[y, x] = np.int16(conv_value) # 결과를 int16으로 변환
print("Feature Map:\n", output_data)

Feature Map:
 [[-9  1]
 [ 0 -7]]


In [ ]:
import numpy as np
array = np.array([1,2]) #원본 이미지
padded_array = np.pad(array,[(1,1)],constant_values=0)
print(padded_array)

[0 1 2 0]


In [ ]:
import numpy as np
array = np.array([[1, 2], [3, 4]]) # 초기 배열 생성
print('--------패딩이 없는 원본 -------')
padded_array = np.pad(array, [(0, 0), (0, 0)], constant_values=0)
print(padded_array)
print('--------첫번째 차원인 행 차원의 앞과 뒤에 1개씩 패딩 -------')
padded_array = np.pad(array, [(1, 1), (0, 0)], constant_values=0)
print(padded_array)

--------패딩이 없는 원본 -------
[[1 2]
 [3 4]]
--------첫번째 차원인 행 차원의 앞과 뒤에 1개씩 패딩 -------
[[0 0]
 [1 2]
 [3 4]
 [0 0]]


In [ ]:
print('--------두번째 차원인 열 차원의 앞과 뒤에 1개씩 패딩-------')
padded_array = np.pad(array, [(0, 0), (1, 1)], constant_values=0)
print(padded_array)
print('--------첫번째 차원, 두번째 차원 모두 1개씩 패딩-------')
padded_array = np.pad(array, [(1, 1), (1, 1)], constant_values=0)
print(padded_array)
print('--------두번째 차원인 열 차원의 앞과 뒤에 2개씩 패딩 -------')
padded_array = np.pad(array, [(0, 0), (2, 2)], constant_values=0)
print(padded_array)

--------두번째 차원인 열 차원의 앞과 뒤에 1개씩 패딩-------
[[0 1 2 0]
 [0 3 4 0]]
--------첫번째 차원, 두번째 차원 모두 1개씩 패딩-------
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]
--------두번째 차원인 열 차원의 앞과 뒤에 2개씩 패딩 -------
[[0 0 1 2 0 0]
 [0 0 3 4 0 0]]


In [ ]:
import numpy as np
x = np.random.randint(low=0, high=101, size=(9, 3, 5, 5))
print(x.shape)
print(x)

(9, 3, 5, 5)
[[[[  1  31  53   1  37]
   [ 45  43  59  36  64]
   [ 19  96  41   0  53]
   [ 88  55  26  58  73]
   [  0  24  97  87  62]]

  [[ 26  72  41 100  10]
   [ 55   4  45   4  68]
   [ 49  90  68  82  98]
   [ 85  39  73  65  98]
   [ 47  10  77  95  87]]

  [[ 67  96  70  68  84]
   [ 10  11   8  72  73]
   [ 22  85  32  31  16]
   [ 92  89  55  46  13]
   [ 78  66  47  47  58]]]


 [[[ 66   8  45  57   2]
   [ 94  12  23  56  69]
   [ 72  68  69  77  76]
   [ 15  79  13  94  75]
   [ 13  49  29  29  43]]

  [[ 98  85  91  75  44]
   [  7  85  18  42   7]
   [ 32  57  73  96   5]
   [ 32  96  61  51  56]
   [ 10  49  97  65  22]]

  [[ 36  74  39  15  23]
   [ 99  84  38  61   8]
   [ 25   4  57  81  99]
   [ 27  31  87  23  62]
   [ 14  90  74  89  82]]]


 [[[ 57  33  74  85  35]
   [ 23  99  51  36  23]
   [  7  87  89  45   1]
   [ 79  54  87  42  17]
   [ 99  37  90  27  23]]

  [[ 93  95  91   9  44]
   [ 80  58  10  57  84]
   [ 69  53  95  72  41]
   [  6  92  42  38

In [ ]:
def im2col(img, kh, kw, stride=1, pad=0): # 필터높이(kh), 필터너비(kw), 필터 이동 간격(stride), 패딩 크기(pad)
  N, C, H, W = img.shape # N은 배치 크기, C는 채널 수, H는 이미지의 높이, W는 이미지의 너비
  out_h = (H + 2*pad - kh)//stride + 1 # 출력 데이터의 높이 계산
  out_w = (W + 2*pad - kw)//stride + 1 # 출력 데이터의 너비 계산

  padded_img = np.pad(array=img, pad_width=[(0,0), (0,0), (pad, pad), (pad, pad)]) # 높이와 너비 차원에만 pad값으로 패딩 적용
  col = np.zeros((N, C, kh, kw, out_h, out_w)) # (배치 크기, 채널 수, 필터 높이, 필터 너비, 출력 높이, 출력 너비)로 결과 배열 초기화

  for y in range(kh): # 필터 커널이 가질 수 있는 모든 높이 위치에 대하여 탐색
    y_max = y + stride*out_h # 해당 필터의 현재 높이 위치에서 이미지 데이터에 접근할 범위의 끝 계산
    for x in range(kw): # 필터 커널이 가질 수 있는 모든 너비 위치에 대하여 탐색
      x_max = x + stride*out_w # 해당 필터의 현재 너비 위치에서 이미지 데이터에 접근할 범위의 끝 계산
      col[:, :, y, x, :, :] = padded_img[:, :, y:y_max:stride, x:x_max:stride] # 현재 필터 위치(y, x)에 해당하는 데이터 추출하여 결과 배열에 입력

  col = col.transpose(0, 4, 5, 1, 2, 3).reshape(N*out_h*out_w, -1) # 합성곱을 단순한 행렬곱셈으로 처리할 수 있도록 구조 변경
  return col

In [ ]:
def im2col_test(img, kh, kw, stride=1, pad=0):
  N, C, H, W = img.shape
  out_h = (H + 2*pad - kh) // stride + 1 # 2
  out_w = (W + 2*pad - kw) // stride + 1 # 2
  padded_img = np.pad(array=img, pad_width=[(0, 0), (0, 0), (pad, pad), (pad, pad)])
  col = np.zeros((N, C, kh, kw, out_h, out_w))
  print("입력 전:\n", col, '\n--------------')

  for y in range(kh):
    y_max = y + stride * out_h
    for x in range(kw):
      x_max = x + stride * out_w
      col[:, :, y, x, :, :] = padded_img[:, :, y:y_max:stride, x:x_max:stride]
      print(f'col[:, :, {y}, {x}, :, :]:')
      print(col[:, :, y, x, :, :], '\n--------------')
  return col


In [ ]:
# 작은 크기의 입력 데이터로 테스트
x1 = np.array([[[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]]]) # 1개의 배치, 1개의 채널, 3x3 이미지
result = im2col_test(x1, kh=2, kw=2, stride=1, pad=0)
print("Final result:\n", result)

입력 전:
 [[[[[[0. 0.]
     [0. 0.]]

    [[0. 0.]
     [0. 0.]]]


   [[[0. 0.]
     [0. 0.]]

    [[0. 0.]
     [0. 0.]]]]]] 
--------------
col[:, :, 0, 0, :, :]:
[[[[1. 2.]
   [4. 5.]]]] 
--------------
col[:, :, 0, 1, :, :]:
[[[[2. 3.]
   [5. 6.]]]] 
--------------
col[:, :, 1, 0, :, :]:
[[[[4. 5.]
   [7. 8.]]]] 
--------------
col[:, :, 1, 1, :, :]:
[[[[5. 6.]
   [8. 9.]]]] 
--------------
Final result:
 [[[[[[1. 2.]
     [4. 5.]]

    [[2. 3.]
     [5. 6.]]]


   [[[4. 5.]
     [7. 8.]]

    [[5. 6.]
     [8. 9.]]]]]]


In [ ]:
x1 = np.random.rand(9, 3, 5, 5) # (9, 3, 5, 5) shape로 난수 생성 (배치크기, 채널수,필터높이, 필터너비)
col1 = im2col(x1, kh=5, kw=5, stride=1, pad=0)
print(col1.shape) # (9, 75) (배치크기x출력높이x출력너비, 채널수x필터높이x필터너비)
#4차원 데이터가 2차원 데이터로 잘 변형되었다
#동일한 필터를 가지는 경우 배치 크기를 늘려보면 그만큼 행이 늘어난다
x2 = np.random.rand(90, 3, 5, 5) # (90, 3, 5, 5)
col2 = im2col(x2, 5, 5, stride=1, pad=0)
print(col2.shape)

(9, 75)
(90, 75)


In [ ]:
import numpy as np
def fil2col(kernel):
  filter_num, channel_num, filter_height, filter_width = kernel.shape
  col = filters.reshape(filter_num, channel_num * filter_height * filter_width)
  return col

In [ ]:
# 6개의 필터가 있고 각 필터가 3개의 채널을 가지며, 필터의 크기는 5x5
filters = np.random.rand(6, 3, 5, 5)
# 필터를 2차원 행렬로 변환
fil_col = fil2col(filters)
print(fil_col.shape)

(6, 75)


In [ ]:
#이미지 데이터와 필터를 모두 2차원 데이터로 만들어 합성곱(행렬연산)을 준비한다

N, C, H, W = 1, 3, 5, 5 # 1개의 이미지, 3개의 채널, 5x5 크기의 이미지
F, kh, kw, stride, pad = 6, 3, 3, 1, 1 # 6개의 필터, 3x3 필터 크기, 스트라이드 1, 패딩 1

input_data = np.random.rand(N, C, H, W) # 이미지 데이터 생성
filters = np.random.rand(F, C, kh, kw) # 필터 가중치 생성

img_col = im2col(input_data, kh, kw, stride, pad) # im2col() 적용
print("im2col 결과:\n", img_col.shape) # (배치 크기x출력 높이x출력 너비, 채널 수x필터 높이x필터 너비)의 2D 출력

fil_col = fil2col(filters) # fil2col() 적용
print("fil2col 결과:\n", fil_col.shape) # (필터 수, 채널 수x필터 높이x필터 너비)의 2D 출력

im2col 결과:
 (25, 27)
fil2col 결과:
 (6, 27)


In [ ]:
fil_col.T.shape

(27, 6)

In [ ]:
# fil_col의 두 번째 차원 (채널 수x필터 높이x필터 너비)는 img_col의 역시 두 번째 차원 (채널 수x필터 높이x필터 너비)와 일치
# 행렬 곱을 이루려면 앞쪽 행렬의 열 수와 뒷쪽 행렬의 행 수가 일치해야 하므로 fil_col을 전치시킨다
conv_out = np.dot(img_col, fil_col.T) # 결과는 (배치크기x출력높이x출력너비, 필터 수)
print("합성곱 연산 결과:\n", conv_out.shape)
print(conv_out)

합성곱 연산 결과:
 (25, 6)
[[2.8158863  3.65297222 2.86323302 3.53995954 2.63313036 2.14327597]
 [5.9556511  4.9992831  5.36607396 6.50522226 4.39585213 5.34961415]
 [5.78727225 4.94378074 5.29167655 6.37354972 4.18380235 6.03654422]
 [5.21167975 4.20174398 5.05965704 6.28389839 4.39590358 5.30601587]
 [3.24580759 1.99066866 3.24672171 2.97383756 2.7429797  3.1358703 ]
 [4.10747261 6.46705338 4.76288054 5.71524795 4.75876256 6.06689162]
 [7.75481088 7.44379461 8.37821917 8.25410156 7.08557811 8.11449971]
 [7.52598642 7.5814311  7.79798762 7.91975179 7.71915723 7.49059791]
 [6.64248868 5.98963748 7.41304879 6.86505169 6.90222923 6.82205262]
 [4.46744989 3.71724439 4.56143446 3.3610873  4.00422938 4.67107379]
 [4.83915107 5.98379499 5.02269684 5.89136356 4.63669549 5.14997386]
 [7.20918566 7.24478024 7.29058897 7.63747202 6.77308062 7.96286568]
 [7.66978147 6.68895595 7.51220528 7.93365988 7.53076715 6.85113216]
 [6.36777146 5.98119683 6.29843204 6.11541939 5.79265402 6.33536251]
 [4.9466992  3